#!/bin/bash
if [ "$PLAYONLINUX" = "" ]
then   
        exit 0
fi

source "$PLAYONLINUX/lib/sources" 

cp -a $SCRIPT_DIRECTORY/../wineversion/4-LeagueOfLegendsCSMT-amd64 $REPERTOIRE/wine//4-LeagueOfLegendsCSMT-amd64

exit
